### ISSUE TITLE
Consider making it a gem

### ISSUE THREAD

**Issue by rubyFeedback** [JHero23/ruby-sinatra-starter-app#1]
I would recommend to make this into a gem too, so that installation becomes easier.

As for a name, perhaps:

    jhero-sinatra-tutorial
    jhero_sinatra_tutorial

or something like that.

And then perhaps even self-serve this through sinatra for people to follow; e. g. with sub-routes such as "step1", "step2" etc... to link between them like a chapter in a book.

**Comment by JHeroGR** [comment]
Thank you, I will keep that into consideration for a final version. For right now, this is just to introduce people to ruby programming and how it works in  a web development environment, so making it into a gem would be something more advanced. I appreciate the suggestion though, will look into it in the future.
